# Generated by Django 5.2.13 on 2026-05-05 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking_new', 'New booking'), ('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled'), ('payment_success', 'Payment success'), ('review_new', 'New review'), ('message_new', 'New message'), ('generic', 'Generic')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
