# Generated by Django 5.2.13 on 2026-05-05 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homestays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='homestays.homestay'),
        ),
        migrations.AddField(
            model_name='homestayamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestay_links', to='homestays.amenity'),
        ),
        migrations.AddField(
            model_name='homestayamenity',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestay_amenities', to='homestays.homestay'),
        ),
        migrations.AddField(
            model_name='homestayimage',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homestays.homestay'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='homestays.homestay'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together={('homestay', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='homestayamenity',
            unique_together={('homestay', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'homestay')},
        ),
    ]
